cards = {
    'Dominion' : {
        # 'Měďák' : { 'name_en' : 'Copper', 'image' : None, 'kingdom_card' : False, 'type' : 'treasure', 'subtype' : None, 'price' : 0, 'value' : 1, 'actions' : None, 'translation' : None },
        # 'Stříbrňák' : { 'name_en' : 'Silver', 'image' : None, 'kingdom_card' : False, 'type' : 'treasure', 'subtype' : None, 'price' : 3, 'value' : 2, 'actions' : None },
        # 'Zlaťák' : { 'name_en' : 'Gold', 'image' : None, 'kingdom_card' : False, 'type' : 'treasure', 'subtype' : None, 'price' : 6, 'value' : 3, 'actions' : None },

        # 'Statek' : { 'name_en' : 'Estate', 'image' : None, 'kingdom_card' : False, 'type' : 'victory', 'subtype' : None, 'price' : 2, 'value' : 1, 'actions' : None },
        # 'Vévodství' : { 'name_en' : 'Duchy', 'image' : None, 'kingdom_card' : False, 'type' : 'victory', 'subtype' : None, 'price' : 5, 'value' : 3, 'actions' : None },
        # 'Provincie' : { 'name_en' : 'Province', 'image' : None, 'kingdom_card' : False, 'type' : 'victory', 'subtype' : None, 'price' : 8, 'value' : 6, 'actions' : None },

        # 'Kletba' : { 'name_en' : 'Curse', 'image' : None, 'kingdom_card' : False, 'type' : 'curse', 'subtype' : None, 'price' : 0, 'value' : -1, 'actions' : None },
#---------------------------------------------------------------
        ## 'Hradní příkop' : { 'name_en' : 'Moat', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : 'reaction', 'price' : 2, 'value' : 0, 'actions' : { 'add_cards' : 2, 'moat' : None }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 2 karty' }, 2 : { 'style' : 'small', 'text' : 'Pokud některý z hráčů zahrajte kartu' }, 3 : { 'style' : 'small', 'text' : 'útoku, můžete se bránit tak, že ukážete' }, 4 : { 'style' : 'small', 'text' : 'tuto kartu z ruky. Pokud tak učiníte,' }, 5 : { 'style' : 'small', 'text' : 'útoku jste se ubránili.' }}]},
        ## 'Kaple' : { 'name_en' : 'Chapel', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 2, 'value' : 0, 'actions' : { 'chapel' : None }, 'translation' : [{ 1 : { 'style' : 'small', 'text' : 'Zahoďte až 4 karty z ruky' }, 2 : { 'style' : 'small', 'text' : 'na smetiště' }}]},
        ## 'Sklepení' : { 'name_en' : 'Cellar', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 2, 'value' : 0, 'actions' : { 'add_actions' : 1, 'cellar' : None }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 1 akce' }, 2 : { 'style' : 'small', 'text' : '' }, 3 : { 'style' : 'small', 'text' : 'Odložte na svůj odkládací balíček' }, 4 : { 'style' : 'small', 'text' : 'libovolný počet karet z ruky.' }, 5 : { 'style' : 'small', 'text' : '+1 karta za každou odloženou kartu' }}]},

        ## 'Vesnice' : { 'name_en' : 'Village', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 3, 'value' : 0, 'actions' : { 'add_cards' : 1, 'add_actions' : 2 }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 1 karta' }, 2 : { 'style' : 'big', 'text' : '+ 2 akce' }}]},
        ## 'Dřevorubec' : { 'name_en' : 'Woodcutter', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 3, 'value' : 0, 'actions' : { 'add_buys' : 1, 'add_treasure' : 2 }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 1 nákup' }, 2 : { 'style' : 'big', 'text' : '+ 2€' }}]},
        ## 'Kancléř' : { 'name_en' : 'Chancellor', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 3, 'value' : 0, 'actions' : { 'add_treasure' : 2, 'chancellor' : None }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 2€' }, 2 : { 'style' : 'small', 'text' : '' }, 3 : { 'style' : 'small', 'text' : 'Můžete okamžitě přesunout' }, 4: { 'style' : 'small', 'text' : 'svůj balíček na svůj odkládací balíček.' }}]},
        ## 'Dílna' : { 'name_en' : 'Workshop', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 3, 'value' : 0, 'actions' : { 'workshop' : None }, 'translation' : [{ 1 : { 'style' : 'small', 'text' : 'Vezměte si kartu' }, 2 : { 'style' : 'small', 'text' : 'o ceně nejvýše 4€' }}]},

        ## 'Zahrady' : { 'name_en' : 'Gardens', 'image' : None, 'kingdom_card' : True, 'type' : 'victory', 'subtype' : None, 'price' : 4, 'value' : 999, 'actions' : { 'to_do' : None }, 'translation' : [{ 1 : { 'style' : 'small', 'text' : 'Karta má cenu 1 vítězný bod' }, 2 : { 'style' : 'small', 'text' : 'za každých 10 karet ve vašem' }, 3 : { 'style' : 'small', 'text' : 'balíčku (zaokrouhleno dolů).' }}]},
        ## 'Úředník' : { 'name_en' : 'Bureaucrat', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : 'attack', 'price' : 4, 'value' : 0, 'actions' : { 'to_do' : None }, 'translation' : [{ 1 : { 'style' : 'small', 'text' : 'Získáváte 1 stříbrňák, který umístíte' }, 2 : { 'style' : 'small', 'text' : 'jako vrchní kartu svého balíčku.' }, 3 : { 'style' : 'small', 'text' : 'Všichni ostatní hráči vyloží 1 kartu' }}, { 4 : { 'style' : 'small', 'text' : 's vítěznými body z ruky a umístí ji' }}, { 5 : { 'style' : 'small', 'text' : 'navrch svého balíčku (nebo odhalí' }},{ 6 : { 'style' : 'small', 'text' : 'ruku bez vítězných bodů' }}]},
        # 'Zloděj' : { 'name_en' : 'Thief', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : 'attack', 'price' : 4, 'value' : 0, 'actions' : { 'to_do' : None }, 'translation' : [{ 1 : { 'style' : 'small', 'text' : 'Všichni ostatní hráči ukážou' }, 2 : { 'style' : 'small', 'text' : 'vrchní 2 karty ze svého balíčku.' }, 3 : { 'style' : 'small', 'text' : 'Pokud přitom narazí na karty peněz,' }, 4 : { 'style' : 'small', 'text' : 'zahodí jednu podle tvého výběru.' }, 5 : { 'style' : 'small', 'text' : 'Zloděj získává libovolné množství' }, 6 : { 'style' : 'small', 'text' : 'zahozených karet. Hráči poté' }, 7 : { 'style' : 'small', 'text' : 'odloží zbylé odkryté karty na svůj' }, 8 : { 'style' : 'small', 'text' : 'odkládací balíček.' }}]},
        ## 'Hostina' : { 'name_en' : 'Feast', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 4, 'value' : 0, 'actions' : { 'feast' : None }, 'translation' : [{ 1 : { 'style' : 'small', 'text' : 'Zahoďte tuto kartu na smetiště.' }, 2 : { 'style' : 'small', 'text' : 'Vezměte si ze stolu kartu' }, 3 : { 'style' : 'small', 'text' : 'o max. ceně 5€' }}]},
        # 
        ## 'Milice' : { 'name_en' : 'Militia', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : 'attack', 'price' : 4, 'value' : 0, 'actions' : { 'add_treasure' : 2, 'militia' : None }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 2€' }, 2 : { 'style' : 'small', 'text' : '' }, 3 : { 'style' : 'small', 'text' : 'Všichni ostatní hráči odloží karty tak,' }, 4: { 'style' : 'small', 'text' : 'aby jim zbyly v ruce 3 karty' }}]},
        ## 'Kovárna' : { 'name_en' : 'Smithy', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 4, 'value' : 0, 'actions' : { 'add_cards' : 3 }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 3 karty' }}]},
        'Špion' : { 'name_en' : 'Spy', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : 'attack', 'price' : 4, 'value' : 0, 'actions' : { 'to_do' : None }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 1 karta' }}, { 2 : { 'style' : 'big', 'text' : '+ 1 akce' }}, { 3 : { 'style' : 'small', 'text' : 'Všichni hráči (včetně tebe) ukážou' }}, { 4 : { 'style' : 'small', 'text' : 'vrchní kartu ze svého balíčku a podle' }}, { 5 : { 'style' : 'small', 'text' : 'tvojí volby ji buď vrátí zpět, nebo' }},{ 6 : { 'style' : 'small', 'text' : 'odloží na svůj odkládací balíček.' }}]},
        ## 'Trůnní sál' : { 'name_en' : 'Throne_Room', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 4, 'value' : 0, 'actions' : { 'throne_room' : None }, 'translation' : [{ 1 : { 'style' : 'small', 'text' : 'Vyberte si 1 akční kartu z ruky' }, 2 : { 'style' : 'small', 'text' : 'a zahrajte ji dvakrát.' }}]},
        ## 'Přestavba' : { 'name_en' : 'Remodel', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 4, 'value' : 0, 'actions' : { 'remodel' : None }, 'translation' : [{ 1 : { 'style' : 'small', 'text' : 'Zahoďte 1 kartu z ruky na smetiště.' }, 2 : { 'style' : 'small', 'text' : 'Získáváte kartu o ceně až o 2€ větší,' }, 3 : { 'style' : 'small', 'text' : 'něž je cena zahozené karty.' }}]},

        ## Moneylender
        ## 'Knihovna' : { 'name_en' : 'Library', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 5, 'value' : 0, 'actions' : { 'library' : None }, 'translation' : [{ 1 : { 'style' : 'small', 'text' : 'Dolízněte si karty tak, abyste jich měli' }, 2 : { 'style' : 'small', 'text' : 'v ruce 7. Můžete dávat stranou akční' }, 3 : { 'style' : 'small', 'text' : 'karty, které byste přitom získali.' }, 4 : { 'style' : 'small', 'text' : 'Po skončení lízání odložte tyto karty' }, 5 : { 'style' : 'small', 'text' : 'na svůj odkládací balíček.' }}]},
        ## 'Čarodějnice' : { 'name_en' : 'Witch', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : 'attack', 'price' : 5, 'value' : 0, 'actions' : { 'to_do' : None }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 2 karty' }, 2 : { 'style' : 'small', 'text' : '' }, 3 : { 'style' : 'small', 'text' : 'Všichni ostatní hráči si vezmou' }, 4: { 'style' : 'small', 'text' : '1 kartu kletby' }}]},
        ## 'Jarmark' : { 'name_en' : 'Festival', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 5, 'value' : 0, 'actions' : { 'add_actions' : 2, 'add_buys' : 1, 'add_treasure' : 2 }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 2 akce' }, 2 : { 'style' : 'big', 'text' : '+ 1 nákup' }, 3 : { 'style' : 'big', 'text' : '+ 2€' }}]},
        ## 'Laboratoř' : { 'name_en' : 'Laboratory', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 5, 'value' : 0, 'actions' : { 'add_cards' : 2, 'add_actions' : 1 }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 2 karty' }, 2 : { 'style' : 'big', 'text' : '+ 1 akce' }}]},
        ## 'Trh' : { 'name_en' : 'Market', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 5, 'value' : 0, 'actions' : { 'add_cards' : 1, 'add_actions' : 1, 'add_buys' : 1, 'add_treasure' : 1 }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 1 karta' }, 2 : { 'style' : 'big', 'text' : '+ 1 akce' }, 3 : { 'style' : 'big', 'text' : '+ 1 nákup' }, 4: { 'style' : 'small', 'text' : '+ 1€' }}]},
        ## 'Důl' : { 'name_en' : 'Mine', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 5, 'value' : 0, 'actions' : { 'mine' : None }, 'translation' : [{ 1 : { 'style' : 'small', 'text' : 'Zahoďte kartu pěněz z ruky' }, 2 : { 'style' : 'small', 'text' : 'na smetiště. Vezměte si do ruky' }, 3 : { 'style' : 'small', 'text' : 'kartu peněz až o 3€ dražší.' }}]},
        ##'Zasedání rady' : { 'name_en' : 'Council_Room', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 5, 'value' : 0, 'actions' : { 'to_do' : None }, 'translation' : [{ 1 : { 'style' : 'big', 'text' : '+ 4 karty' }, 2 : { 'style' : 'big', 'text' : '+ 1 nákup' }, 3 : { 'style' : 'small', 'text' : '' }, 4: { 'style' : 'small', 'text' : 'Všichni ostatní hráči si líznou kartu.' }}]},

        # 'Dobrodruh' : { 'name_en' : 'Adventurer', 'image' : None, 'kingdom_card' : True, 'type' : 'action', 'subtype' : None, 'price' : 6, 'value' : 0, 'actions' : { 'to_do' : None }, 'translation' : [{ 1 : { 'style' : 'small', 'text' : 'Ukazuj karty ze svého balíčku, dokud' }, 2 : { 'style' : 'small', 'text' : 'nenarazíš na 2 karty peněz. Obě karty' }, 3 : { 'style' : 'small', 'text' : 'peněz si vezmi do ruky, ostatní odkryté' }, 4: { 'style' : 'small', 'text' : 'karty odlož na svůj odkládací balíček.' }}]},
    }
}






